{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "job-pod-reaper.fullname" . }}-list-namespaces
  labels:
    {{- include "job-pod-reaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "job-pod-reaper.fullname" . }}-list-namespaces
subjects:
- kind: ServiceAccount
  name: {{ include "job-pod-reaper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.config.reapNamespaces }}
{{- range (split "," .Values.config.reapNamespaces) }}
---
{{- if eq . "all" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "job-pod-reaper.fullname" $ }}
  labels:
    {{- include "job-pod-reaper.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "job-pod-reaper.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "job-pod-reaper.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace | quote }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-{{ include "job-pod-reaper.fullname" $ }}-rolebinding
  namespace: {{ . | quote }}
  labels:
    {{- include "job-pod-reaper.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "job-pod-reaper.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "job-pod-reaper.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
