apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-pod-reaper.fullname" . }}
  labels:
    {{- include "job-pod-reaper.labels" . | nindent 4 }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "job-pod-reaper.selectorLabels" . | nindent 4 }}
