name: Release

on:
  push:
    tags:
      - '*'

jobs:
  set-output:
    name: Set Output
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
    outputs:
      version: ${{ steps.version.outputs.version }}
  release:
    needs: [set-output]
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: creekorful/goreportcard-action@v1.0
      - name: Make Release
        env:
          VERSION: ${{ needs.set-output.outputs.version }}
        run: |
          rm -rf release
          make release
          make release-notes > release/release-notes.out
          cat release/release-notes.out
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --debug --release-notes=release/release-notes.out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.set-output.outputs.version }}
